#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/a07f0aed-4632-4759-a4c5-b970864cbbab 
  
  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch aC;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#define touchSensor 4
#define relayPin 15
#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(relayPin,OUTPUT);
    pinMode(touchSensor,INPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  int touchval = digitalRead(touchSensor);
  if(touchval == 1){
    if(aC == 1){
      aC =0;
      digitalWrite(relayPin,aC);
      digitalWrite(5,aC);
      Serial.print("StateChanged:");
      Serial.println(aC);
      
    }
    else{
      aC = 1;
      digitalWrite(relayPin,aC);
      digitalWrite(5,aC);
      Serial.print("StateChanged:");
      Serial.println(aC);
    }
  }
  else{
    delay(1);
  }
  
}



/*
  Since AC is READ_WRITE variable, onACChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onACChange()  {
  // Add your code here to act upon AC change
  digitalWrite(relayPin,aC);
  digitalWrite(5,aC);
  Serial.print("Relay State:");
  Serial.println(aC);
}